# Generated by Django 2.2.4 on 2019-08-31 14:40

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(new_building__isnull=True).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building),
    ]
